In [4]:
import pandas as pd

from surprise import Dataset, Reader
from surprise import SVD, NMF
from surprise.model_selection import cross_validate, train_test_split, GridSearchCV

### Load data

In [5]:
df = pd.read_csv("data/ratings_beauty.csv")

reader = Reader(rating_scale=(1, 10))
data = Dataset.load_from_df(df[['UserId', 'ProductId', 'Rating']], reader)

In [6]:
print('Number of ratings: %d\nNumber of ProductIds: %d\nNumber of users: %d' % (len(df), len(df['Rating'].unique()), len(df['UserId'].unique())))

Number of ratings: 2023070
Number of ProductIds: 5
Number of users: 1210271

## Apply SVD

In [7]:
trainset, testset = train_test_split(data, test_size=0.2)

model = SVD(n_factors=80, n_epochs=20, lr_all=0.005, reg_all=0.2)
model.fit(trainset)
predictions = model.test(testset)

In [8]:
df.head(5)

           UserId   ProductId  Rating   Timestamp
0  A39HTATAQ9V7YF  0205616461     5.0  1369699200
1  A3JM6GV9MNOF9X  0558925278     3.0  1355443200
2  A1Z513UWSAAO0F  0558925278     5.0  1404691200
3  A1WMRR494NWEWV  0733001998     4.0  1382572800
4  A3IAAVS479H7M7  0737104473     1.0  1274227200

In [9]:
df[df['UserId'] == 'A39HTATAQ9V7YF']

                 UserId   ProductId  Rating   Timestamp
0        A39HTATAQ9V7YF  0205616461     5.0  1369699200
899125   A39HTATAQ9V7YF  B002OVV7F0     3.0  1369699200
969482   A39HTATAQ9V7YF  B0031IH5FQ     5.0  1369699200
1499680  A39HTATAQ9V7YF  B006GQPZ8E     4.0  1369699200

In [10]:
model.predict('A39HTATAQ9V7YF', '0205616461' )

Prediction(uid='A39HTATAQ9V7YF', iid='0205616461', r_ui=None, est=np.float64(4.416949330995847), details={'was_impossible': False})

In [11]:
predictions

[Prediction(uid='A1YF3HLZ5ORJW5', iid='B006QO4BRM', r_ui=4.0, est=np.float64(3.972918296127552), details={'was_impossible': False}),
 Prediction(uid='AB8NIIM9UPMC7', iid='B000IOAAQ2', r_ui=5.0, est=np.float64(4.0259595548640394), details={'was_impossible': False}),
 Prediction(uid='A2I9EYS0ZPPP0J', iid='B001KYRP80', r_ui=5.0, est=np.float64(3.7025652069033415), details={'was_impossible': False}),
 Prediction(uid='A1M9MY9F95L3JI', iid='B004SPDEWE', r_ui=5.0, est=np.float64(4.249346753716983), details={'was_impossible': False}),
 Prediction(uid='A2T80QPEG88K86', iid='B002JCSLXA', r_ui=5.0, est=np.float64(3.9167545876907295), details={'was_impossible': False}),
 Prediction(uid='A2JP02PCZ7YCZE', iid='B008ZFDOMS', r_ui=4.0, est=np.float64(4.215006167255477), details={'was_impossible': False}),
 Prediction(uid='A1XRW9OP3U63V8', iid='B001A1P9QS', r_ui=4.0, est=np.float64(3.6973760832626272), details={'was_impossible': False}),
 Prediction(uid='A37O8LMWANI620', iid='B002HFKPLU', r_ui=5.0, est=np.float64(4.2549429640891345), details={'was_impossible': False}),
 Prediction(uid='A106HE3B6Y579', iid='B00315B4CY', r_ui=5.0, est=np.float64(4.070961585100975), details={'was_impossible': False}),
 Prediction(uid='A1SM7RRARZSGJC', iid='B005LQ5QP2', r_ui=5.0, est=np.float64(4.223454218898146), details={'was_impossible': False}),
 Prediction(uid='A1FXB9RV33HUIL', iid='B00AWPOE1E', r_ui=5.0, est=np.float64(4.282475892045988), details={'was_impossible': False}),
 Prediction(uid='A1JDF8XEZP0UY1', iid='B000YK1YAQ', r_ui=4.0, est=np.float64(3.7384052819958917), details={'was_impossible': False}),
 Prediction(uid='A1VLJYZS0B9KPC', iid='B000IOFQWK', r_ui=4.0, est=np.float64(4.18008769439464), details={'was_impossible': False}),
 Prediction(uid='A280IZV4UTUE81', iid='B005F4EFMA', r_ui=5.0, est=np.float64(4.443940637408351), details={'was_impossible': False}),
 Prediction(uid='AVXPKFP18SI6D', iid='B008VTKIRW', r_ui=4.0, est=np.float64(4.307564438754034), details={'was_impossible': False}),
 Prediction(uid='A2XTR785Q4OR9E', iid='B000GXBGIG', r_ui=5.0, est=np.float64(4.122002643133439), details={'was_impossible': False}),
 Prediction(uid='AIYW96OTWV7CX', iid='B005GWAR9G', r_ui=4.0, est=np.float64(4.370818267197077), details={'was_impossible': False}),
 Prediction(uid='AZYP7IN1HG9QV', iid='B00BTG4NW0', r_ui=2.0, est=np.float64(3.9566954179752662), details={'was_impossible': False}),
 Prediction(uid='AIV0LJLYLKOZR', iid='B000MT0T5U', r_ui=5.0, est=np.float64(4.071057336458612), details={'was_impossible': False}),
 Prediction(uid='A3Y50NAGVLMD', iid='B000BJ1CGQ', r_ui=5.0, est=np.float64(3.6213955394479798), details={'was_impossible': False}),
 Prediction(uid='AX6VBONGW78SI', iid='B004TSFBNK', r_ui=5.0, est=np.float64(4.852711118929522), details={'was_impossible': False}),
 Prediction(uid='A34FLUM7PVEQZH', iid='B001E96OZ6', r_ui=5.0, est=np.float64(3.9815464549344983), details={'was_impossible': False}),
 Prediction(uid='A3IOCPLIMYDBCD', iid='B0009VNI40', r_ui=4.0, est=np.float64(3.845169412714042), details={'was_impossible': False}),
 Prediction(uid='A30XOWE2VZHCCY', iid='B0009V8N5E', r_ui=1.0, est=np.float64(4.185596766757353), details={'was_impossible': False}),
 Prediction(uid='A6A1P4DQV73XJ', iid='B009D75M8Q', r_ui=4.0, est=np.float64(4.478266728415082), details={'was_impossible': False}),
 Prediction(uid='A1YB9ZYR5ZMEO6', iid='B003HLTTJM', r_ui=1.0, est=np.float64(3.949453889103425), details={'was_impossible': False}),
 Prediction(uid='A36S8COFCPST0P', iid='B000PLUZL8', r_ui=5.0, est=np.float64(4.180099595284829), details={'was_impossible': False}),
 Prediction(uid='AJNFEL0YVS7WS', iid='B004667U2A', r_ui=5.0, est=np.float64(4.149222905898557), details={'was_impossible': False}),
 Prediction(uid='A1ISQLTAPGFESW', iid='B001MA0QY2', r_ui=5.0, est=np.float64(4.210027495186803), details={'was_impossible': False}),
 Prediction(uid='A3W4W6BZM1E8V3', iid='B00C4R3HV6', r_ui=3.0, est=np.float64(3.910208144524865), details={'was_impossible': False}),
 Prediction(uid='A1GW73EI3AY17L', iid='B00198ZOU8', r_ui=5.0, est=np.float64(3.961236137829022), details={'was_impossible': False}),
 Prediction(uid='AJ3TOX03MQNVN', iid='B004I2VYCE', r_ui=4.0, est=np.float64(4.674594929820902), details={'was_impossible': False}),
 Prediction(uid='AV5PO73H7ISL8', iid='B001J9LLX6', r_ui=4.0, est=np.float64(3.9867254342016025), details={'was_impossible': False}),
 Prediction(uid='A25NULIP3O550P', iid='B000CNKJS8', r_ui=5.0, est=np.float64(4.62102287055189), details={'was_impossible': False}),
 Prediction(uid='A3NMP5LF5IO1WG', iid='B00CEOWTFY', r_ui=5.0, est=np.float64(4.148346943012353), details={'was_impossible': False}),
 Prediction(uid='AZ7GSGGKJQAOX', iid='B004INEX3U', r_ui=5.0, est=np.float64(4.394338908713186), details={'was_impossible': False}),
 Prediction(uid='A2EBCKBVQMW2J9', iid='B00B430LXS', r_ui=5.0, est=np.float64(3.9728514776366644), details={'was_impossible': False}),
 Prediction(uid='A3AIKPNQWMBFC1', iid='B001GN783M', r_ui=5.0, est=np.float64(4.241248399494993), details={'was_impossible': False}),
 Prediction(uid='A21R9ALSDQW6IQ', iid='B004PHMVRE', r_ui=3.0, est=np.float64(4.143221096094319), details={'was_impossible': False}),
 Prediction(uid='A2D8TZ7YPQK3P6', iid='B00JNI1DZQ', r_ui=5.0, est=np.float64(4.724069280303538), details={'was_impossible': False}),
 Prediction(uid='A1W9UIP0IF3Y34', iid='B0047IG6BS', r_ui=5.0, est=np.float64(3.8133737942950163), details={'was_impossible': False}),
 Prediction(uid='A22URO0KNILFNF', iid='B00BEKI5JI', r_ui=2.0, est=np.float64(3.717558559559468), details={'was_impossible': False}),
 Prediction(uid='A2D1LPEUCTNT8X', iid='B000F4GIPM', r_ui=2.0, est=np.float64(4.590699473010006), details={'was_impossible': False}),
 Prediction(uid='A17H6HF6K0ZGLI', iid='B0009PVV4A', r_ui=5.0, est=np.float64(4.218122244246803), details={'was_impossible': False}),
 Prediction(uid='A2NXGJXBZWON3U', iid='B007USPWS0', r_ui=5.0, est=np.float64(4.103143310016955), details={'was_impossible': False}),
 Prediction(uid='A1NZXDFJ27KGFE', iid='B001B7GJ2E', r_ui=2.0, est=np.float64(3.8600446928908703), details={'was_impossible': False}),
 Prediction(uid='A1U9P31UI3C6TB', iid='B009GKOW0Y', r_ui=5.0, est=np.float64(4.253104750720994), details={'was_impossible': False}),
 Prediction(uid='ACSG3M34LAZ7F', iid='B0067JF88M', r_ui=5.0, est=np.float64(4.231277032039387), details={'was_impossible': False}),
 Prediction(uid='A2ISJ04OJ316OK', iid='B0058E3XJI', r_ui=5.0, est=np.float64(4.324417237699284), details={'was_impossible': False}),
 Prediction(uid='A12XKQFH1S15IR', iid='B004TSFE6Y', r_ui=5.0, est=np.float64(4.370679061680948), details={'was_impossible': False}),
 Prediction(uid='A3232H7J6URX9D', iid='B006ZEV036', r_ui=4.0, est=np.float64(4.2358996872121635), details={'was_impossible': False}),
 Prediction(uid='A3GNEPABXLTKON', iid='B00B213B9I', r_ui=5.0, est=np.float64(4.771617683198468), details={'was_impossible': False}),
 Prediction(uid='A1VLORU49CXB93', iid='B000Y8X0LE', r_ui=5.0, est=np.float64(3.964361891209105), details={'was_impossible': False}),
 Prediction(uid='A2EX0HDNZ64LBS', iid='B0001EL0CW', r_ui=5.0, est=np.float64(4.481327346166632), details={'was_impossible': False}),
 Prediction(uid='A224WFP5JLZULH', iid='B003H897AQ', r_ui=4.0, est=np.float64(3.1965234368640933), details={'was_impossible': False}),
 Prediction(uid='AFY4WRJ7DNEQ4', iid='B0019UZ3ZM', r_ui=5.0, est=np.float64(4.229515099595749), details={'was_impossible': False}),
 Prediction(uid='A3SUO3L9WJPD1P', iid='9790792190', r_ui=4.0, est=np.float64(4.148346943012353), details={'was_impossible': False}),
 Prediction(uid='A3SZN9KXSAVN3Y', iid='B000L596FE', r_ui=5.0, est=np.float64(4.500300752594288), details={'was_impossible': False}),
 Prediction(uid='AL2SAX2P280A3', iid='B00026CZC8', r_ui=3.0, est=np.float64(4.465239168809567), details={'was_impossible': False}),
 Prediction(uid='A3SNLUNLGATQIJ', iid='B005DKRRAS', r_ui=5.0, est=np.float64(3.960056972096366), details={'was_impossible': False}),
 Prediction(uid='A15CFPZONN9LMR', iid='B002BWOXYE', r_ui=5.0, est=np.float64(3.9120808641629434), details={'was_impossible': False}),
 Prediction(uid='A1KLVME4HSVFQV', iid='B003V21WO2', r_ui=5.0, est=np.float64(4.211328688349051), details={'was_impossible': False}),
 Prediction(uid='A37U28WE3XM3HV', iid='B000VF023E', r_ui=5.0, est=np.float64(4.270777992537563), details={'was_impossible': False}),
 Prediction(uid='A2NKRT4FQ175LP', iid='B0043NRUBM', r_ui=5.0, est=np.float64(4.1894245781445205), details={'was_impossible': False}),
 Prediction(uid='A2X6PQG7V4SJTV', iid='B006J7FSE6', r_ui=5.0, est=np.float64(4.1691213209071805), details={'was_impossible': False}),
 Prediction(uid='AN9Q1YIUZP8QB', iid='B000J2652Q', r_ui=5.0, est=np.float64(4.166044628343105), details={'was_impossible': False}),
 Prediction(uid='A3M7WNF69VXE6B', iid='B000FS05VG', r_ui=5.0, est=np.float64(4.08934620178933), details={'was_impossible': False}),
 Prediction(uid='AA24R4ZO8PEL7', iid='B000LSBZA0', r_ui=5.0, est=np.float64(4.093282511663594), details={'was_impossible': False}),
 Prediction(uid='A32LVWUY84J0HV', iid='B007BLN17K', r_ui=1.0, est=np.float64(3.4411348835293465), details={'was_impossible': False}),
 Prediction(uid='A173XZ11N20RKB', iid='B007XKER2W', r_ui=5.0, est=np.float64(4.461283787406301), details={'was_impossible': False}),
 Prediction(uid='A33HFXGB7SJLDY', iid='B003YXUK2I', r_ui=5.0, est=np.float64(3.922889290537704), details={'was_impossible': False}),
 Prediction(uid='A2AHO27TUS2H8C', iid='B009M1K396', r_ui=4.0, est=np.float64(4.55701632019645), details={'was_impossible': False}),
 Prediction(uid='A1S72ZJTI1Q5JN', iid='B003F2T0M4', r_ui=1.0, est=np.float64(4.2421647839704635), details={'was_impossible': False}),
 Prediction(uid='A2YP40BO6O1DVK', iid='B00D3CN1T4', r_ui=5.0, est=np.float64(4.3494652335098305), details={'was_impossible': False}),
 Prediction(uid='A3FYJJGMJBDRU5', iid='B0009V1YR8', r_ui=5.0, est=np.float64(3.5843875991143883), details={'was_impossible': False}),
 Prediction(uid='A3J9HMTOR85770', iid='B00AM8923G', r_ui=5.0, est=np.float64(3.6076150589802465), details={'was_impossible': False}),
 Prediction(uid='A14O97YTA40GIX', iid='B002AC2RW0', r_ui=3.0, est=np.float64(4.676530190302704), details={'was_impossible': False}),
 Prediction(uid='A2FFVXH62SWXGB', iid='B002QFGQAK', r_ui=4.0, est=np.float64(4.369395589793213), details={'was_impossible': False}),
 Prediction(uid='A6X1O3A5C5FX1', iid='B00AE078YM', r_ui=1.0, est=np.float64(3.7380433633614634), details={'was_impossible': False}),
 Prediction(uid='A1HNFO4R3RNI5O', iid='B00ANH56BS', r_ui=5.0, est=np.float64(3.196398842972903), details={'was_impossible': False}),
 Prediction(uid='A12HIC5JSX1PHY', iid='B0020MM8WO', r_ui=5.0, est=np.float64(4.441761936357618), details={'was_impossible': False}),
 Prediction(uid='A3BMBJBGEWXWOJ', iid='B001LVA0XO', r_ui=5.0, est=np.float64(3.989104985254954), details={'was_impossible': False}),
 Prediction(uid='A2T0W63H6J0RE8', iid='B003FBTYAI', r_ui=3.0, est=np.float64(3.6925714746150176), details={'was_impossible': False}),
 Prediction(uid='ADFMRFSSTLHNR', iid='B001C6H6F8', r_ui=5.0, est=np.float64(4.270400995925987), details={'was_impossible': False}),
 Prediction(uid='A3V1SSYRTVPVOV', iid='B001TJXI5U', r_ui=4.0, est=np.float64(4.334144840990096), details={'was_impossible': False}),
 Prediction(uid='APYJHYZOVNHGR', iid='B004LJ0ZK6', r_ui=5.0, est=np.float64(4.133679952885093), details={'was_impossible': False}),
 Prediction(uid='A1MHDPMS8RRJH8', iid='B005VRA5YI', r_ui=3.0, est=np.float64(4.118850459655537), details={'was_impossible': False}),
 Prediction(uid='A120GZ4NMR0533', iid='B0007DHMBK', r_ui=4.0, est=np.float64(3.638476994467658), details={'was_impossible': False}),
 Prediction(uid='A3LQ6H27FEK85U', iid='B0045WDQFA', r_ui=4.0, est=np.float64(4.384388177350581), details={'was_impossible': False}),
 Prediction(uid='A2CCPJ0NR2Z072', iid='B000PY6F6E', r_ui=5.0, est=np.float64(4.319718652944611), details={'was_impossible': False}),
 Prediction(uid='A37D4VGNBN4LCV', iid='B00F4ANYOA', r_ui=5.0, est=np.float64(3.9985599169523867), details={'was_impossible': False}),
 Prediction(uid='A1WZT4KZCBTTID', iid='B003T18TE6', r_ui=5.0, est=np.float64(4.395242546905), details={'was_impossible': False}),
 Prediction(uid='APX7PAPK2R65S', iid='B0067F8BBM', r_ui=1.0, est=np.float64(3.651741075604741), details={'was_impossible': False}),
 Prediction(uid='A330K6V2Q1YONY', iid='B009O5BC22', r_ui=5.0, est=np.float64(3.9310936756642914), details={'was_impossible': False}),
 Prediction(uid='A2K6ELXMUGAG8J', iid='B00G7TZXPK', r_ui=1.0, est=np.float64(4.148346943012353), details={'was_impossible': False}),
 Prediction(uid='A3GQL2SQQTYVUB', iid='B000NW4LDM', r_ui=4.0, est=np.float64(4.230935399200916), details={'was_impossible': False}),
 Prediction(uid='A2GJNGCR0OJY9Q', iid='B00683JILU', r_ui=3.0, est=np.float64(3.3758158118836343), details={'was_impossible': False}),
 Prediction(uid='A2QOSQCXSCB0X6', iid='B0085Y85VE', r_ui=5.0, est=np.float64(4.148346943012353), details={'was_impossible': False}),
 Prediction(uid='A3TAUTLAZR5NB0', iid='B001QMCFEA', r_ui=5.0, est=np.float64(4.053749424032524), details={'was_impossible': False}),
 Prediction(uid='A1K0BU5PS0BXJW', iid='B00IAMTLS2', r_ui=5.0, est=np.float64(4.458926921823506), details={'was_impossible': False}),
 Prediction(uid='A22TA00NX63RC7', iid='B003UM6TJG', r_ui=5.0, est=np.float64(4.65452910387511), details={'was_impossible': False}),
 Prediction(uid='A34BZM6S9L7QI4', iid='B000W3QDJ2', r_ui=4.0, est=np.float64(4.63362304053399), details={'was_impossible': False}),
 Prediction(uid='A3TKPLR454JZZ1', iid='B001MUFKWA', r_ui=5.0, est=np.float64(3.90963145183306), details={'was_impossible': False}),
 Prediction(uid='AO9KC2NCUO3X1', iid='B000SI2T0S', r_ui=4.0, est=np.float64(4.175969656204067), details={'was_impossible': False}),
 Prediction(uid='A3GWRJ8B5TK2T2', iid='B00875KPGY', r_ui=5.0, est=np.float64(4.2624484537633), details={'was_impossible': False}),
 Prediction(uid='A1J3G4P075INYY', iid='B00B9QUDZG', r_ui=4.0, est=np.float64(3.8692870862733706), details={'was_impossible': False}),
 Prediction(uid='A8NY9QXZNXUW3', iid='B0098QVTYS', r_ui=5.0, est=np.float64(4.280648046238356), details={'was_impossible': False}),
 Prediction(uid='A1PM7YGXKH7GO0', iid='B004Q27KRO', r_ui=5.0, est=np.float64(3.8917548112238385), details={'was_impossible': False}),
 Prediction(uid='ADH7OF6WIIQC1', iid='B001G0JNT2', r_ui=5.0, est=np.float64(4.574147390178254), details={'was_impossible': False}),
 Prediction(uid='A18JUY7UKPWC4A', iid='B007V8YIWK', r_ui=5.0, est=np.float64(4.148346943012353), details={'was_impossible': False}),
 Prediction(uid='A2G39FU8VVZ1RA', iid='B000DIN39Y', r_ui=5.0, est=np.float64(4.518892674429291), details={'was_impossible': False}),
 Prediction(uid='AWQT55RY54DGQ', iid='B00D67IANS', r_ui=3.0, est=np.float64(4.28249611266009), details={'was_impossible': False}),
 Prediction(uid='A3IJMHNNK0T4D0', iid='B00APEOAIY', r_ui=3.0, est=np.float64(4.147808514818725), details={'was_impossible': False}),
 Prediction(uid='A1OBQ671C8BMEJ', iid='B002T3V29Y', r_ui=5.0, est=np.float64(4.041449955740815), details={'was_impossible': False}),
 Prediction(uid='A1EBDIGUCNYDLR', iid='B008S6INZC', r_ui=5.0, est=np.float64(4.3960905187310475), details={'was_impossible': False}),
 Prediction(uid='A2C7V5O6MI3QQH', iid='B004IOJGH2', r_ui=2.0, est=np.float64(3.9671450535012376), details={'was_impossible': False}),
 Prediction(uid='A36ZTVVUCBONMG', iid='B005MYK58G', r_ui=2.0, est=np.float64(3.552438052421374), details={'was_impossible': False}),
 Prediction(uid='A30WOXPI820KFJ', iid='B00BFCN4U0', r_ui=5.0, est=np.float64(4.934852888819726), details={'was_impossible': False}),
 Prediction(uid='A3COJS1XX8MF4Q', iid='B004YBW5T0', r_ui=5.0, est=np.float64(4.220197451969742), details={'was_impossible': False}),
 Prediction(uid='A31UFCD9MILMJW', iid='B0011DRT9K', r_ui=3.0, est=np.float64(3.7635965036898384), details={'was_impossible': False}),
 Prediction(uid='A30CB5LCKQXOAE', iid='B0040PDKPI', r_ui=4.0, est=np.float64(4.749975332519566), details={'was_impossible': False}),
 Prediction(uid='A2Q0IYYKKULIQG', iid='B000C1W6TK', r_ui=5.0, est=np.float64(4.236305978312729), details={'was_impossible': False}),
 Prediction(uid='A22QOZZLLIMW6I', iid='B00A76CPUA', r_ui=5.0, est=np.float64(3.8248572653016213), details={'was_impossible': False}),
 Prediction(uid='A2IW6BNKSG1RV8', iid='B003JOF52W', r_ui=4.0, est=np.float64(3.936595106845551), details={'was_impossible': False}),
 Prediction(uid='A1C2GEZK2L8DC9', iid='B009VK4IDK', r_ui=5.0, est=np.float64(3.959375357613375), details={'was_impossible': False}),
 Prediction(uid='A3RUAOEC7SW0P5', iid='B000B91MYS', r_ui=1.0, est=np.float64(3.4367752689903335), details={'was_impossible': False}),
 Prediction(uid='A1L2RT7KBNK02K', iid='B0091391CK', r_ui=2.0, est=np.float64(3.918554620611482), details={'was_impossible': False}),
 Prediction(uid='A3IS26RE3EB0S8', iid='B002HM3AJ2', r_ui=1.0, est=np.float64(3.175219811763527), details={'was_impossible': False}),
 Prediction(uid='A2NFXV3ZYFSUZW', iid='B006H6O2JG', r_ui=5.0, est=np.float64(4.602059890403002), details={'was_impossible': False}),
 Prediction(uid='A14BLCOEUB5NJ5', iid='B00B4TR3KG', r_ui=5.0, est=np.float64(4.442669291529426), details={'was_impossible': False}),
 Prediction(uid='A3EOO8KA722AN4', iid='B0017U10SI', r_ui=5.0, est=np.float64(4.285147781260104), details={'was_impossible': False}),
 Prediction(uid='A39UVGP0S8214Y', iid='B001UDRR0W', r_ui=3.0, est=np.float64(3.577455521429799), details={'was_impossible': False}),
 Prediction(uid='AELO31HVXRMW3', iid='B000V85BAU', r_ui=1.0, est=np.float64(4.038223526577558), details={'was_impossible': False}),
 Prediction(uid='A1TUPMBV35L79G', iid='B000K9NZJE', r_ui=5.0, est=np.float64(4.417463499531735), details={'was_impossible': False}),
 Prediction(uid='A1ZH9LWMX5UCFJ', iid='B001ET6YGU', r_ui=5.0, est=np.float64(4.415329196554946), details={'was_impossible': False}),
 Prediction(uid='A376AOV5QHTY4U', iid='B0040MM0AC', r_ui=5.0, est=np.float64(4.414511386876755), details={'was_impossible': False}),
 Prediction(uid='ANLY1Q1F25E5Q', iid='B000C1W49M', r_ui=4.0, est=np.float64(4.28463431839161), details={'was_impossible': False}),
 Prediction(uid='AME4ZNOUR6VRL', iid='B008RVYJS8', r_ui=5.0, est=np.float64(4.2342537542563505), details={'was_impossible': False}),
 Prediction(uid='A1N55FJGRCLLFW', iid='B006K4B3L0', r_ui=5.0, est=np.float64(3.962869197881888), details={'was_impossible': False}),
 Prediction(uid='A1H62JXIRV5X36', iid='B00F5GZQ76', r_ui=5.0, est=np.float64(4.1536807751617255), details={'was_impossible': False}),
 Prediction(uid='AONSJJQ382R81', iid='B0010SYLB0', r_ui=5.0, est=np.float64(4.152953597925495), details={'was_impossible': False}),
 Prediction(uid='A36MLCRPYNRSXP', iid='B001FORJ8G', r_ui=4.0, est=np.float64(3.7984277060214695), details={'was_impossible': False}),
 Prediction(uid='A2K7KYMFH4SC5E', iid='B004K4LF2O', r_ui=5.0, est=np.float64(4.096399702922572), details={'was_impossible': False}),
 Prediction(uid='A1ADVYRGIDVB5H', iid='B0069FDR96', r_ui=4.0, est=np.float64(4.040925156499385), details={'was_impossible': False}),
 Prediction(uid='A26QVWJ29TTEVU', iid='B000NSSLI2', r_ui=5.0, est=np.float64(4.122435763894171), details={'was_impossible': False}),
 Prediction(uid='AK9MWBK2KHPGO', iid='B000J56B2W', r_ui=1.0, est=np.float64(2.805782013601644), details={'was_impossible': False}),
 Prediction(uid='A3TMLCA5W14X8J', iid='B00027DMI8', r_ui=5.0, est=np.float64(3.8764717801467032), details={'was_impossible': False}),
 Prediction(uid='AXW7KZTR1HF81', iid='B0092429BI', r_ui=5.0, est=np.float64(3.9213204280716036), details={'was_impossible': False}),
 Prediction(uid='A1DJCH9JL6PZFA', iid='B001VMM234', r_ui=1.0, est=np.float64(3.9988122319240893), details={'was_impossible': False}),
 Prediction(uid='AERG1EZ3HFDDZ', iid='B001LXQ5ZO', r_ui=4.0, est=np.float64(4.301836004463424), details={'was_impossible': False}),

In [12]:
# Perform cross-validation
cv_results = cross_validate(model, data, measures=['RMSE', 'MAE'], cv=5, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    1.2472  1.2448  1.2446  1.2459  1.2436  1.2452  0.0012
MAE (testset)     0.9810  0.9796  0.9799  0.9806  0.9788  0.9800  0.0008
Fit time          29.72   28.74   29.20   31.43   30.01   29.82   0.92
Test time         3.68    3.56    3.54    3.67    3.61    3.61    0.05

In [13]:
def get_recommendations(model, user_id, n_recommendations=5):   
    # Get all product IDs
    all_product_ids = df['ProductId'].unique()
    
    # Get the products the user has already rated
    rated_products = df[df['UserId'] == user_id]['ProductId'].unique()
    
    # Filter out the products the user has already rated
    unrated_products = [pid for pid in all_product_ids if pid not in rated_products]
    
    # Predict ratings for the unrated products
    predictions = [model.predict(user_id, pid) for pid in unrated_products]
    
    # Sort predictions by estimated rating in descending order
    predictions.sort(key=lambda x: x.est, reverse=True)
    
    # Get the top N recommendations
    top_recommendations = predictions[:n_recommendations]
    
    return [(pred.iid, pred.est) for pred in top_recommendations]

In [14]:
get_recommendations(model, 'A39HTATAQ9V7YF', n_recommendations=5)

[('B004AI5756', np.float64(4.871982181775004)),
 ('B001F0RBRE', np.float64(4.8511754679879635)),
 ('B0018QHU6W', np.float64(4.822819207260653)),
 ('B008CYHZS6', np.float64(4.820807796293814)),
 ('B00466VJ04', np.float64(4.820402616843522))]